# Generated by Django 6.0.3 on 2026-04-10 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_a', models.IntegerField(default=0)),
                ('goles_b', models.IntegerField(default=0)),
                ('jugado', models.BooleanField(default=False)),
                ('equipo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_a', to='aplicacion.equipo')),
                ('equipo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_b', to='aplicacion.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugados', models.IntegerField(default=0)),
                ('ganados', models.IntegerField(default=0)),
                ('empatados', models.IntegerField(default=0)),
                ('perdidos', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.equipo')),
            ],
        ),
    ]
